name: Deploy Web (Next.js) to Azure App Service
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          # point cache at your app's lockfile
          cache-dependency-path: apps/web/pnpm-lock.yaml

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      # Install at the repo root or just the app – choose ONE.
      # If your lockfile lives under apps/web, simplest is install inside apps/web:
      - name: Install (web)
        working-directory: apps/web
        run: pnpm install --no-frozen-lockfile

      - name: Build (web)
        working-directory: apps/web
        run: pnpm build

      - name: Prepare deploy folder (standalone)
        working-directory: apps/web
        run: |
          rm -rf ../site && mkdir -p ../site
          cp -r .next/standalone/* ../site/
          mkdir -p ../site/.next/static
          cp -r .next/static ../site/.next/static
          cp -r public ../site/public

      - name: Zip artifact
        working-directory: apps
        run: |
          cd site
          zip -r ../app.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: apps/app.zip
