name: Deploy Web (Next.js) to Azure App Service

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm & enable Corepack
        run: |
          npm install -g pnpm@10
          corepack enable
          corepack prepare pnpm@10 --activate
          pnpm -v

      # Install once at repo root (workspace-aware)
      - name: Install deps (root)
        run: pnpm install --frozen-lockfile

      # Prisma client generation (uses SQL Server URL, NOT sqlite)
      - name: Prisma generate (apps/web)
        working-directory: apps/web
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm prisma generate

      # Build the Next.js app (standalone)
      - name: Build (apps/web)
        working-directory: apps/web
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
        run: pnpm build

      # Guard: ensure standalone output exists
      - name: Assert standalone output exists
        working-directory: apps/web
        run: |
          test -f .next/standalone/server.js || (echo "ERROR: .next/standalone/server.js not found. Ensure next.config has output: 'standalone'." && exit 1)

      # Prepare minimal runtime artifact (standalone + static + public)
      - name: Prepare deploy folder
        working-directory: apps/web
        run: |
          rm -rf ../site && mkdir -p ../site
          cp -r .next/standalone/* ../site/
          mkdir -p ../site/.next/static
          cp -r .next/static ../site/.next/static
          cp -r public ../site/public

      - name: Zip artifact
        working-directory: apps
        run: |
          cd site
          zip -r ../app.zip .

      # Deploy with Service Principal (no publish profile needed)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set startup command (node server.js)
        run: |
          az webapp config set -g hackhub-rgv -n "${{ secrets.AZURE_WEBAPP_NAME }}" --startup-file "node server.js"

      - name: Deploy to Azure Web App (zip deploy)
        run: |
          az webapp deploy \
            --resource-group hackhub-rgv \
            --name "${{ secrets.AZURE_WEBAPP_NAME }}" \
            --src-path apps/app.zip \
            --type zip

      - name: Restart app
        run: az webapp restart -g hackhub-rgv -n "${{ secrets.AZURE_WEBAPP_NAME }}"