name: Deploy Web (Next.js) to Azure App Service
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Node (no pnpm caching here to avoid the PATH race)
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install pnpm first so it's on PATH
      - name: Install pnpm
        run: npm install -g pnpm@10

      # (Optional) Also activate via Corepack; shows pnpm version for sanity
      - name: Enable pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@10 --activate
          pnpm -v

      # Install dependencies in the app directory (where your lockfile lives)
      - name: Install dependencies
        working-directory: apps/web
        run: pnpm install --no-frozen-lockfile

      # Build Next.js
      - name: Build
        working-directory: apps/web
        run: pnpm build

      # Package Next.js standalone output for App Service
      - name: Prepare deploy folder (standalone)
        working-directory: apps/web
        run: |
          rm -rf ../site && mkdir -p ../site
          cp -r .next/standalone/* ../site/
          mkdir -p ../site/.next/static
          cp -r .next/static ../site/.next/static
          cp -r public ../site/public

      - name: Zip artifact
        working-directory: apps
        run: |
          cd site
          zip -r ../app.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: apps/app.zip
